### ISSUE TITLE
ServerSigns sends an additional click event when interacting with a ServerSign button.

### ISSUE THREAD

**Issue by mibby** [serversigns/ServerSigns#44]
I have a ServerSign attached to a Birch Button that runs the command ``/parkour join`` to join a parkour gamemode called Walk in the Park.  (https://www.spigotmc.org/resources/walk-in-the-park-infinite-parkour-1-16-x.87226/)

When I right click the button while my hotbar inventory is hovering over slot 9, it opens the Walk in the Park options menu item (which is given to slot 9 on join) immediately after the command is ran by ServerSigns and teleporting you to the parkour gamemode in the new world. This happens because ServerSigns seems to send an additional right click interact event so the other plugin registers it as trying to open the menu. 

I tried attaching the command ``/parkour join`` to another plugin that handles commands on button interact (ButtonWarps) and it does not have this problem.

I have tested this with ``cancel_mode: ALWAYS`` & ``cancel_mode: NEVER``.

**Comment by EpiCanard** [comment]
Hello,

The cancel mode is here only to disable redstone signal on click on the button.

I can reproduce with Walk in the Park, and the "bug" come mainly because the plugin teleport the player and the right click is made after the player is teleported.

I verified in SVS and the cancel check is done before the execution of the commands so I really don't know why this action done after the teleportation. I will say it is caused by minecraft, but I really don't know.

**Comment by mibby** [comment]
Any ideas why the plugin ButtonWarp doesn't have this problem when it's functionally similar (command on interact) to SVS? Surely this must indicate there is an interact bug somewhere in ServerSigns.

**Comment by EpiCanard** [comment]
I will continue to search but I really don't know since event is cancelled just after you clicked on it.

**Comment by EpiCanard** [comment]
I investigate and it will not be possible. It is a bug with minecraft where the right click and the teleport are on the same tick.
The only solution is to execute the command on the next tick but it break the flow of SVS command tasks.

**Example :**
```yaml
commands:
  '0':
    command: Plop
    type: MESSAGE
  '1':
    command: /parkour join
    type: PLAYER_COMMAND
  '2':
    command: Plip
    type: MESSAGE
```
If I run the command on next tick it will do in order :
1 - Plop
2 - Plip
3 - Teleport to parkour

Instead of
1 - Plop
2 - Teleport to parkour
3 - Plip


So if you want to "fix" this issue, add a delay on the command parkour join.
`/svs <add> [d:1s] parkour join`

**Comment by mibby** [comment]
Thanks, that does seem to be a workaround to the problem. Is it possible to delay less than 1s though? For example delaying for 10 ticks. A full second is a bit slow. Being able to granularly order / delay commands by ticks would help reduce perceived user delay when tasks run.

i.e.

```
commands:
  '0':
    command: Plop
    type: MESSAGE
  '1':
    command: /parkour join
    type: PLAYER_COMMAND
    delay: 5 ticks
  '2':
    command: Plip
    type: MESSAGE
    delay: 10 ticks
```
